continuation_prompt = "â¯â¯â¯ "

[character]
success_symbol = "[âœ“](green) [â¯](red)[â¯](yellow)[â¯](green)"
error_symbol = "[â…¹](red) [â¯](red)[â¯](red)[â¯](red)"

[directory]
read_only = " ï ½ "

[git_branch]
symbol = "ï˜ "

[git_metrics]
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false
added_style="green"

[git_state]
style = "yellow"

[package]
symbol = "ï£– "
disabled = true

[sudo]
symbol = "ğŸ§‘ğŸ¼â€ğŸ’»"
disabled = false
